parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'balance-service-postgres'

doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        dbname: '%env(DATABASE_NAME)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/BalanceService/Domain'
                prefix: 'Iqoption\BalanceService\Domain'
                alias: BalanceService
            Common:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/BalanceService/Common'
                prefix: 'Iqoption\BalanceService\Common'
                alias: BalanceServiceCommon
